import './globals.css'
import ThemeRegistry from '@/theme/ThemeRegistry'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextAuthProvider } from '@/providers/next-auth-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <NextAuthProvider>
          <body className={inter.className}>{children}</body>
        </NextAuthProvider>
      </ThemeRegistry>
    </html>
  )
}
